### ISSUE TITLE
Bug - URL column

### ISSUE THREAD

**Issue by hildeirin** [fivetran/dbt_facebook_ads_source#10]
Hi! Thanks for a great package!! 
I think maybe the column "url" should be removed from the yaml file, as it is not created in staging, and not requested in the creative_history sql file? We have a enabled persisted docs, and this column therefore creates an error. 
(I am a bit new to this, so forgive me if there is something I am missing here..)

https://github.com/fivetran/dbt_facebook_ads_source/blob/8ddfa6336019f6d339e4c8d7247b368e3d0ed736/models/stg_facebook_ads.yml#L80

**Comment by fivetran-joemarkiewicz** [comment]
Hi @hildeirin, thanks for opening this issue!

I just checked this package with `persist_docs` enabled on my Snowflake warehouse and did indeed see the same URL error you mentioned. I just pushed a few changes removing the URL and other fields that are not included in the final staging model. These changes were tested by myself using the `persist_docs` config enabled and I was able to see the runs succeed!

Prior to having this PR merged and included in the next release you can test the working branch to ensure it succeeds on your end. If you would like to do so, you can copy/paste the below snippet into your `packages.yml` and run the code off the working branch.

```yml
packages:
  - git: https://github.com/fivetran/dbt_facebook_ads_source.git
    revision: bug/persist-docs-fields
    warn-unpinned: false
```

Let me know if you have any questions. Thanks again!

**Comment by hildeirin** [comment]
Hi @fivetran-joemarkiewicz! Thanks so much for the help and advice! :) 🙌🏼 🙌🏼 

Would you please advice me on how I could write this code if I want the facebook ads / transform package to use this revision? I now get an error (as that package depends on the source package): 

```
Encountered an error:
Found duplicate project "facebook_ads_source". This occurs when a dependency has the same project name as some other dependency.
```

Again, thanks for the help. Much appreciated! :)

**Comment by fivetran-joemarkiewicz** [comment]
We actually just cut the `v0.2.2` release of this package that includes this Issue fix which should be live on the dbt hub by tomorrow morning! 

I will post back here when that is the case. Once the release is live you won't have to do anything on your end (such as change the package dependency) to successfully run the package. You will be able to keep the initial dependencies.

**Comment by fivetran-joemarkiewicz** [comment]
`v0.2.2` is now live on the [dbt hub](https://hub.getdbt.com/fivetran/facebook_ads_source/latest/)! You should be able to rerun `dbt deps` and fetch the most recent changes and run the package successfully. 

Let me know if you have any further questions.

**Comment by hildeirin** [comment]
This is awesome, @fivetran-joemarkiewicz! Thank you so much for the help, and the new release! :)
