### ISSUE TITLE
[Bug] basic_ads does not exist

### ISSUE THREAD

**Issue by johnf** [fivetran/dbt_facebook_ads_source#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The models reference a basic_ads table which isn't currently created by the connector

### Expected behavior

No error

### dbt Project configurations

Nothing specific to this package

### Package versions

packages:
  - package: fivetran/facebook_ads_source
    version: [">=0.5.0", "<0.6.0"]

### What database are you using dbt with?

postgres

### dbt Version

Core:

installed: 1.2.3
latest: 1.3.1 - Update available!
Your version of dbt-core is out of date!
You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:

postgres: 1.2.3 - Update available!
At least one plugin is out of date or incompatible with dbt-core.
You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @johnf thanks for opening this issue.

The basic_ads table is actual a custom report that you will need to add within the Fivetran connector. We should include steps on how to add this custom report within our [pre-requisites](https://github.com/fivetran/dbt_facebook_ads_source#step-1-prerequisites) steps of our README.

Additionally, we are working with our engineering team to try and have the basic_ads as a default report out of the box. However, for the time being you will need to manually add the report from the Fivetran connector UI. 

Let me know if you have any other questions!

**Comment by johnf** [comment]
@fivetran-joemarkiewicz Thanks. I noticed it is in that section. I completely missed it, though. I think because in almost all the other packages, there are only the first two points which are sort of redundant, so I tend to skip over that section blindly.
