### ISSUE TITLE
QUESTION - basic_ad table is not there in facebook_ads schema

### ISSUE THREAD

**Issue by sriram23kmm** [fivetran/dbt_facebook_ads_source#7]
using Facebook ads connector i pulled all tables to my warehouse  when i using dbt_facebook_ads_source package in my project it was excepting `basic_ad` table which was not there in my schema

**Comment by fivetran-kristin** [comment]
@sriram23kmm Is it safe to assume you figured out this problem? I'm curious, were you possibly using the old Facebook connector, and this was a matter of setting up our new facebook connector?

**Comment by wuservices** [comment]
@fivetran-kristin I'm running into this issue too. I'm currently trialing Fivetran and set up the newer Facebook Ads connector. Do I need to add the pre-built report `BASIC_AD` and choose `Day` for aggregation and name the table `basic_ad`?

**Comment by fivetran-jamie** [comment]
hey there @wuservices thanks for reaching out -- we'll be pushing some instruction around this in the README (PR https://github.com/fivetran/dbt_facebook_ads_source/pull/13)

**Comment by macmietek** [comment]
Hi, basic_ad table is still not syncing. I followed all the steps listed in the tutorial. I even tried configuring basic_ad table manually using the Fivetran documentation. It didn't work.
