### ISSUE TITLE
FEATURE - Indicate how to configure Fivetran connector

### ISSUE THREAD

**Issue by alejobs** [fivetran/dbt_facebook_ads_source#8]
**Are you a Fivetran customer?** 
Yes. Alejo Buxeres, Wallbox Chargers

**Is your feature request related to a problem? Please describe.**
If we don't configure Fivetran Facebook Ads connector correctly, basic_ad table is missing

**Describe the solution you'd like**
Describe in the README how to configure Fivetran Facebook Ads connector (see: https://fivetran.com/docs/applications/facebook-ads). I suppose we need to configure a Table called "basic_ad" with the pre-configured report "BASIC_AD" at a day granularity.

**Describe alternatives you've considered**
 

**Additional context**

**Please indicate the level of urgency and business impact of this request** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
HI @alejobs thanks for opening this Request.

This is a great idea that we have actually received multiple requests and questions on. I will add this task to our next sprint to tackle and integrate some more fleshed out documentation on how to obtain all necessary tables to run this package. I will respond back here when we assign this task during our next sprint and will continue communication from there.

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
The above PR has been merged and we can close out this Issue.
